#!/usr/bin/env node
// Local development script - replaces placeholders with .env values
// Run this before starting local server
require('dotenv').config();
const fs = require('fs');
const path = require('path');

console.log('🔧 Setting up local development environment...');

// Read .env file
const envPath = path.join(__dirname, '.env');
if (!fs.existsSync(envPath)) {
    console.error('❌ .env file not found!');
    console.error('📝 Copy .env.example to .env and fill in your values');
    process.exit(1);
}

// Get environment variables
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;
const STORAGE_BUCKET = process.env.STORAGE_BUCKET || 'Portfolio';
const STORAGE_URL = process.env.STORAGE_URL;

// Validate
if (!SUPABASE_URL || !SUPABASE_ANON_KEY || !STORAGE_URL) {
    console.error('❌ Missing required environment variables in .env');
    console.error('Required: SUPABASE_URL, SUPABASE_ANON_KEY, STORAGE_URL');
    process.exit(1);
}

console.log('✅ Environment variables loaded from .env');

// Create a local config file
const configPath = path.join(__dirname, 'supabase-config.local.js');
const configContent = `// Local development configuration
// This file is auto-generated by setup-local.js
// DO NOT commit this file (it's in .gitignore)

const SUPABASE_URL = '${SUPABASE_URL}';
const SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';
const STORAGE_BUCKET = '${STORAGE_BUCKET}';
const STORAGE_URL = '${STORAGE_URL}';

// Initialize Supabase client
const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// Export for use in other files
window.supabase = supabaseClient;
window.SUPABASE_URL = SUPABASE_URL;
window.SUPABASE_KEY = SUPABASE_ANON_KEY;
window.STORAGE_BUCKET = STORAGE_BUCKET;
window.STORAGE_URL = STORAGE_URL;

// Generate Signed URL for Private Files
async function getSignedUrl(filePath, expiresIn = 3600) {
    try {
        if (!filePath) throw new Error('No file path provided');
        
        console.log('🔐 Generating signed URL for:', filePath);
        
        let cleanPath = filePath
            .replace(/^https?:\\/\\/[^\\/]+\\.storage\\.supabase\\.co\\/storage\\/v1\\/s3\\/Portfolio\\//, '')
            .replace(/^https?:\\/\\/[^\\/]+\\/storage\\/v1\\/object\\/public\\/[Pp]ortfolio\\//, '')
            .replace(/^https?:\\/\\/[^\\/]+\\/storage\\/v1\\/object\\/sign\\/[Pp]ortfolio\\//, '')
            .replace(/^[Pp]ortfolio\\//, '')
            .replace(/^\\/*/, '');
        
        console.log('📂 Clean path:', cleanPath);
        
        const { data, error } = await supabaseClient.storage
            .from(STORAGE_BUCKET)
            .createSignedUrl(cleanPath, expiresIn);
        
        if (error) {
            console.error('❌ Signed URL error:', error);
            throw error;
        }
        
        console.log('✅ Signed URL generated:', data.signedUrl);
        return { success: true, url: data.signedUrl };
    } catch (error) {
        console.error('❌ Signed URL generation failed:', error.message);
        return { success: false, error: error.message };
    }
}

window.uploadFile = uploadFile;
window.deleteFile = deleteFile;
window.getSignedUrl = getSignedUrl;

console.log('✅ Supabase initialized (LOCAL MODE)');
`;

fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✅ Local configuration created: supabase-config.local.js');
console.log('');
console.log('📝 To use local development:');
console.log('   1. Replace <script src="supabase-config.js"> with');
console.log('      <script src="supabase-config.local.js"> in HTML files');
console.log('   2. Or use a local web server that can do URL rewriting');
console.log('');
console.log('🚀 Ready for local development!');
console.log('   Run: python -m http.server 8000');
console.log('   Visit: http://localhost:8000');
